# Generated by Django 6.0.1 on 2026-02-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fc_id_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('related_system', models.CharField(choices=[('Biometric Device', 'Biometric Device'), ('YDL CRM', 'YDL CRM')], max_length=50)),
                ('new_functionality', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
