# Generated by Django 6.0.1 on 2026-02-02 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='new_functionality',
        ),
    ]
